import Head from 'next/head'
import Image from 'next/image'
import { Box , Center} from '@chakra-ui/react';
import Hero from '../components/Hero';


export default function Home() {
  return (
    <>
      <Head>
        <title>GROUPE TASSO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/bolo.jpeg" />
      </Head>
      <Hero />
    </>
  )
}
